#!/bin/bash

user=$1;
repo=$2;
loc=${3:-$(pwd)};
path="$loc/$repo";
addr="https://api.github.com/user/repos"

echo "creating repo $path for user $user";

curl -u $user $addr -d '{"name":'\"$repo\"',"private":true}'


mkdir $path && cd $path
git init
touch README.md
touch LICENSE.md
touch .gitignore
git add .
git commit -m "first commit"
git branch -M main
git remote add origin "git@github.com:$user/$repo.git" 
git push -u origin main

